name: "New Pattern Card"
description: "Add a new Alexandrian pattern"
title: "Pattern: "
labels: ["pattern"]
body:
  - type: input
    id: driver
    attributes:
      label: Driver
  - type: textarea
    id: context
    attributes:
      label: Context
  - type: textarea
    id: problem
    attributes:
      label: Problem
  - type: textarea
    id: forces
    attributes:
      label: Forces
  - type: textarea
    id: solution
    attributes:
      label: Solution
  - type: textarea
    id: resulting_context
    attributes:
      label: Resulting Context
  - type: textarea
    id: related_patterns
    attributes:
      label: Related Patterns

